### ISSUE TITLE
Goss (Organ) UI redesign

### ISSUE THREAD

**Issue by jmidt** [bitfieldaudio/OTTO#138]
The Goss (Organ/Hammond) engine has been reworked, so we need a new ui to reflect this. (It was also very simplistic before)

There are 4 controls for the synth:
- Registration/Drawbars (Blue)
- Drive/Compression (Green)
- Keyclick (Yellow)
- Leslie speed and amount (red)

What we have right now is this:
![goss](https://user-images.githubusercontent.com/32618198/69730483-7525d880-1128-11ea-914e-0f8d826070a0.png)
The red dot spins faster and in a bigger circle when increasing the red knob. I kind of like this visual since it effectively conveys both speed and magnitude of the modulation.

The BIGGEST issue is the drawbars. Every step of the blue knob has a different string of 9 numbers, corresponding to the drawbar positions on a typical Hammond organ. It would be cool to draw these in a stylized way, to resemble physical drawbars, perhaps. This is what they look like on an organ:
![Hammond_Magnet_1024x1024](https://user-images.githubusercontent.com/32618198/69730857-19a81a80-1129-11ea-9c38-67c861219a71.jpg)

Feel free to post any ideas or initial designs as comments!

**Comment by ZitromMusic** [comment]
So the keyclick is not binary but continous? Do you change the volume of the effect?
I quite don't get the drawbar function, yet. I've got a combo organ myself, so I understand the feature of drawbars. But how do you want to set the drawbars with only one knob? At least you need two: One for selecting a drawbar and another for changing the parameter of it. Or do you just want to add the other bars as layers on it? That would be a little disappointing in my opinion.

Edit: Now, that I read it another time, I probably understand: You have different presets and select one by changing the blue knob? So there ist no continous way to manipulate the drawbars? That seems alright, since it is just a synth engine.

**Comment by jmidt** [comment]
Yes, the edit is correct. And yes, the keyclick is continuous. If you haven't built the program yet you should do it and play around with it a bit.
